services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:YOUR_APP_KEY
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=sgbr_backend
      - DB_USERNAME=postgres
      - DB_PASSWORD=1234
    depends_on:
      - db
    ports:
      - "9000:9000"

  db:
    image: postgres:14
    container_name: laravel_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: sgbr_backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local